### ISSUE TITLE
Getting error Running model failed: Not found

### ISSUE THREAD

**Issue by dejesus-git** [reneweb/react-native-tensorflow#11]
Hi Im receiving the error 'Running model failed: Not found: FetchOutputs node output: not found'. Not sure what I could be doing wrong I followed the doc and everything installed uneventfully.
`
export default class Album {
async _predict(){
    const tfImageRecognition = new TfImageRecognition({
      model: require('../../assets/retrained_graph.pb'),
      labels: require('../../assets/retrained_labels.txt')
    })

    const results = await tfImageRecognition.recognize({
      image: require('../../assets/1.jpg'),
     })
     .then(r => console.log(r))
     .catch(err => console.log(err))
  }
}
`

**Comment by kentyunge** [comment]
I had a similar issue that was caused by the output name in the library not matching the output name my model used.  You can pass in the output name as a parameter in the recognize function.

`const results = await tfImageRecognition.recognize({
  image: require('../../assets/1.jpg'),
  outputName: 'final_result'
 })
 .then(r => console.log(r))
 .catch(err => console.log(err))`

**Comment by dejesus-git** [comment]
Great, it resolved the issue. Maybe that should be noted on the doc. thanks

**Comment by reneweb** [comment]
It is described in the comment in the example code:
```
outputName: "output", //Optional, defaults to "output"
```
but I agree it could be more explicit and in general the docs are still pretty basic
